### ISSUE TITLE
Year rate

### ISSUE THREAD

**Issue by lucianokrebs** [eric-malachias/irr#1]
Hey, 

Thank you for this amazing library. The 'daily rate' is working perfectly.

I was just wondering what is the right way to get the rate per year.

Thanks in advance!

**Comment by lucianokrebs** [comment]
Just find a good solution (for those who are looking for this):

in order to transform the daily rate into an annual rate:
```javascript
(1 + rate) ** 365 - 1
```

where `rate` is returned from `xirr(data)`

**Comment by eric-malachias** [comment]
That's right!

```typescript
// DAY 0
day0 = initialAmount

// DAY 1
day1 = day0 + day0 * dailyRate // let's call this (1)
// or
day1 = day0 * (1 + dailyRate)

// DAY 2
day2 = day1 * (1 + dailyRate)
// or
day2 = day0 * (1 + dailyRate) ** 2

// DAY N
dayN = day0 * (1 + dailyRate) ** n
// or, re-written in the same format as (1)
dayN = day0 + day0 * ((1 + dailyRate) ** n - 1)
//                   ^^^^^^^^^^^^^^^^^^^^^^^^^ <- rateN
dayN = day0 + day0 * rateN
```
then we get (generic formula):
```typescript
rateN = (1 + dailyRate) ** n - 1
```
and finally, as you correctly deduced:
```typescript
annualRate = rate365 = (1 + dailyRate) ** 365 - 1
```
Curious fact about that formula: even though it was deduced for positive integers, it works for fractional numbers too (even negative numbers, but that's another story). So, if you needed an hourly rate for example, you could get it by doing:
```typescript
hourlyRate = (1 + dailyRate) ** (1 / 24) - 1
```

Thanks for the feedback and I hope this helps!

**Comment by eric-malachias** [comment]
I added a helper function [`convertRate`](https://github.com/eric-malachias/irr#convertrate) for such conversions.
