### ISSUE TITLE
How to use irr() correctly?

### ISSUE THREAD

**Issue by codeofsumit** [eric-malachias/irr#7]
Hi there,
I'm trying to use this package to calculate the IRR for stock investments. Trying it on a simple example where I know the IRR from other tools, I fail to reconstruct it with this library and I believe I'm doing it wrong - can you point me into the right direction?

Here's an example:

Transactions:
2019-04-01: BUY 2x90€ = 180€
2020-04-01: BUY 1x100€ = 100€
Todays worth (2020-04-25): 278,94€

I wanted to use a monthly period, resulting in the following data array and way how I calculate IRR
```js
const data = [-180, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -100, 278.94]
const rate = irr(data)

console.log(rate * 100) // -0.043551589193391305
console.log(convertRate(rate, 'year')) // -0.14700187202666248
```

The expected annualized IRR should be `-0,53%`.
Can you tell me what I'm doing wrong?

Thanks in advance for any guidance and for your work 👍

**Comment by xfl03** [comment]
The best way is calculating it using `xirr`.
```js
const {xirr, convertRate} = require('node-irr')

const data = [
    {amount: -180, date: '20190401'},
    {amount: -100, date: '20200401'},
    {amount: 278.94, date: '20200425'},
]
const daily_rate = xirr(data).rate
console.log((convertRate(daily_rate, 'year') * 100).toFixed(2) + "%")
```

If you do want to use `irr`, the data is income or outcome in months, which cause the rate means mouth rate. So you should change the last line.
```js
console.log(convertRate(rate, 'year', 'month'))
```

**Comment by codeofsumit** [comment]
@xfl03 that works like a charm. Switched to `XIRR`.
Thank you very much 👍
